const DB = [
  {
    id: 1,
    text: "Define drug according to WHO.",
    subject: "Pharmacology",
    topic: "Sources of administration of drugs",
    appearances: [{ year: 2017, month: "January", university: "DU" }],
  },
  {
    id: 2,
    text: "Define drug.",
    subject: "Pharmacology",
    topic: "Sources of administration of drugs",
    appearances: [{ year: 2013, month: "June", university: "DU" }],
  },
  {
    id: 3,
    text: "Define pharmacodynamics.",
    subject: "Pharmacology",
    topic: "Sources of administration of drugs",
    appearances: [{ year: 2010, month: "June", university: "DU" }],
  },
  {
    id: 4,
    text: "What do you mean by Pharmacokinetics?",
    subject: "Pharmacology",
    topic: "Sources of administration of drugs",
    appearances: [
      { year: 2010, month: "June", university: "DU" },
      { year: 2006, month: "September", university: "DU" },
    ],
  },
  {
    id: 5,
    text: "Describe briefly the sources of drugs with examples.",
    subject: "Pharmacology",
    topic: "Sources of administration of drugs",
    appearances: [{ year: 2010, month: "June", university: "DU" }],
  },
  {
    id: 6,
    text: "Write short note on: Pharmacopoeia",
    subject: "Pharmacology",
    topic: "Sources of administration of drugs",
    appearances: [{ year: 2017, month: "January", university: "DU" }],
  },
  {
    id: 7,
    text: "What do you mean by hepatic first pass metabolism?",
    subject: "Pharmacology",
    topic: "First pass metabolism",
    appearances: [{ year: 2009, month: "January", university: "DU" }],
  },
  {
    id: 8,
    text: "Explain first pass metabolism. Enlist four (04) drugs those under go first pass effects.",
    subject: "Pharmacology",
    topic: "First pass metabolism",
    appearances: [{ year: 2017, month: "January", university: "DU" }],
  },
  {
    id: 9,
    text: "Explain with examples of pre systemic elimination of drug.",
    subject: "Pharmacology",
    topic: "First pass metabolism",
    appearances: [{ year: 2011, month: "June", university: "DU" }],
  },
  {
    id: 10,
    text: "Plasma protein binding can influence both pharmacodynamics and pharmacokinetics – explain.",
    subject: "Pharmacology",
    topic: "First pass metabolism",
    appearances: [{ year: 2008, month: "January", university: "DU" }],
  },
  // Added more data for better filtering demo
  {
    id: 11,
    text: "Define Anatomy and its subdivisions.",
    subject: "Anatomy",
    topic: "Introduction to Anatomy",
    appearances: [{ year: 2017, month: "January", university: "DU" }],
  },
  {
    id: 12,
    text: "Describe the anatomical position.",
    subject: "Anatomy",
    topic: "Introduction to Anatomy",
    appearances: [{ year: 2016, month: "May", university: "RU" }],
  },
  {
    id: 13,
    text: "Classify bones with examples.",
    subject: "Anatomy",
    topic: "Osteology",
    appearances: [
      { year: 2017, month: "January", university: "DU" },
      { year: 2015, month: "May", university: "CMU" },
    ],
  },
  {
    id: 14,
    text: "What is Glycolysis? Describe its pathway.",
    subject: "Biochemistry",
    topic: "Carbohydrate Metabolism",
    appearances: [{ year: 2016, month: "May", university: "RU" }],
  },
  {
    id: 15,
    text: "What are the prerequisites for autopsy?",
    subject: "Forensic Medicine",
    topic: "Autopsy",
    appearances: [{ year: 2025, month: "November", university: "DU" }],
  },
];
